# Data Cleaning & Restructuring

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib import style

In [2]:
# To Display all columns 
pd.set_option('display.max_columns', None)

style.use(['science', 'notebook', 'grid'])

In [3]:
dallas_city = pd.read_csv('../dataset/raw/Dallas_City_Data_2021.csv', index_col='ID')
dallas_city.head(5)

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Number,Street,Side,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
A-11786,2,2016-11-30 15:29:48,2016-11-30 21:29:48,32.84365,-96.77463,32.81833,-96.78806,1.915,Between Mockingbird Ln/Exit 3 and Knox St/Hend...,NaN,US-75 S,R,Dallas,Dallas,TX,75205,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11787,2,2016-11-30 15:41:16,2016-11-30 21:41:16,32.84662,-96.63736,32.84640,-96.63711,0.021,At La Prada Dr/Exit 9 - Accident.,NaN,I-635 S,R,Dallas,Dallas,TX,75228,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11794,3,2016-11-30 16:16:05,2016-11-30 22:16:05,32.79385,-96.70278,32.79498,-96.69424,0.502,At Jim Miller Rd/Exit 51 - Accident.,NaN,R L Thornton Fwy E,R,Dallas,Dallas,TX,75228,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11795,3,2016-11-30 16:16:05,2016-11-30 22:16:05,32.85710,-96.77046,32.84623,-96.77330,0.769,Between Caruth Haven Ln/Exit 4 and Lovers Ln/E...,NaN,Southwestern Blvd,R,Dallas,Dallas,TX,75225,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,True,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
A-11798,3,2016-11-30 16:21:05,2016-11-30 22:21:05,32.87684,-96.81001,32.88004,-96.80963,0.222,At Walnut Hill Ln - Accident.,NaN,Dallas North Tollway N,R,Dallas,Dallas,TX,75225,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [4]:
# Closer look at the names of the columns or attributes
dallas_city.columns

Index(['Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng',
       'End_Lat', 'End_Lng', 'Distance(mi)', 'Description', 'Number', 'Street',
       'Side', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [5]:
dallas_city.shape

(41615, 46)

### Make Column names more self-explanatory

In [6]:
dallas_city.rename(columns={'Number': 'Street_Number', 
                            'Street':'Street_Name', 
                            'Side': 'Street_Side'}, inplace=True)
dallas_city.head()

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street_Number,Street_Name,Street_Side,City,County,State,Zipcode,Country,Timezone,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
A-11786,2,2016-11-30 15:29:48,2016-11-30 21:29:48,32.84365,-96.77463,32.81833,-96.78806,1.915,Between Mockingbird Ln/Exit 3 and Knox St/Hend...,NaN,US-75 S,R,Dallas,Dallas,TX,75205,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11787,2,2016-11-30 15:41:16,2016-11-30 21:41:16,32.84662,-96.63736,32.84640,-96.63711,0.021,At La Prada Dr/Exit 9 - Accident.,NaN,I-635 S,R,Dallas,Dallas,TX,75228,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11794,3,2016-11-30 16:16:05,2016-11-30 22:16:05,32.79385,-96.70278,32.79498,-96.69424,0.502,At Jim Miller Rd/Exit 51 - Accident.,NaN,R L Thornton Fwy E,R,Dallas,Dallas,TX,75228,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11795,3,2016-11-30 16:16:05,2016-11-30 22:16:05,32.85710,-96.77046,32.84623,-96.77330,0.769,Between Caruth Haven Ln/Exit 4 and Lovers Ln/E...,NaN,Southwestern Blvd,R,Dallas,Dallas,TX,75225,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,True,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
A-11798,3,2016-11-30 16:21:05,2016-11-30 22:21:05,32.87684,-96.81001,32.88004,-96.80963,0.222,At Walnut Hill Ln - Accident.,NaN,Dallas North Tollway N,R,Dallas,Dallas,TX,75225,US,US/Central,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

### Confirm single-valued columns

In [7]:
dallas_city[['City', 'State', 'Country', 'Timezone']]

             City State Country    Timezone
ID
A-11786    Dallas    TX      US  US/Central
A-11787    Dallas    TX      US  US/Central
A-11794    Dallas    TX      US  US/Central
A-11795    Dallas    TX      US  US/Central
A-11798    Dallas    TX      US  US/Central
...           ...   ...     ...         ...
A-2844612  Dallas    TX      US  US/Central
A-2844627  Dallas    TX      US  US/Central
A-2844632  Dallas    TX      US  US/Central
A-2845067  Dallas    TX      US  US/Central
A-2845068  Dallas    TX      US  US/Central

[41615 rows x 4 columns]

### Note: 

As shown in the previous jupyter notebook in basic exploration of the US-Accidents data and confirmed in the above cell, some columns share the same values all throughout this subset since we extracted Dallas City dataset. <hr>

### Dropping columns

In [8]:
dallas_city.drop(columns=['City', 'State', 'Country', 'Timezone' ], inplace=True)
dallas_city.head(5)

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street_Number,Street_Name,Street_Side,County,Zipcode,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
A-11786,2,2016-11-30 15:29:48,2016-11-30 21:29:48,32.84365,-96.77463,32.81833,-96.78806,1.915,Between Mockingbird Ln/Exit 3 and Knox St/Hend...,NaN,US-75 S,R,Dallas,75205,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11787,2,2016-11-30 15:41:16,2016-11-30 21:41:16,32.84662,-96.63736,32.84640,-96.63711,0.021,At La Prada Dr/Exit 9 - Accident.,NaN,I-635 S,R,Dallas,75228,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11794,3,2016-11-30 16:16:05,2016-11-30 22:16:05,32.79385,-96.70278,32.79498,-96.69424,0.502,At Jim Miller Rd/Exit 51 - Accident.,NaN,R L Thornton Fwy E,R,Dallas,75228,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11795,3,2016-11-30 16:16:05,2016-11-30 22:16:05,32.85710,-96.77046,32.84623,-96.77330,0.769,Between Caruth Haven Ln/Exit 4 and Lovers Ln/E...,NaN,Southwestern Blvd,R,Dallas,75225,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,True,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
A-11798,3,2016-11-30 16:21:05,2016-11-30 22:21:05,32.87684,-96.81001,32.88004,-96.80963,0.222,At Walnut Hill Ln - Accident.,NaN,Dallas North Tollway N,R,Dallas,75225,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [9]:
print(f'The number of columns is reduced to {dallas_city.shape[1]}.')

The number of columns is reduced to 42.

### Checking Missing Values in Dallas City subset

In [10]:
na_count = dallas_city.isna().sum()
missing_val = na_count[dallas_city.isna().sum()>0]
missing_val

Street_Number        26817
Airport_Code             7
Weather_Timestamp       63
Temperature(F)          98
Wind_Chill(F)         7964
Humidity(%)            100
Pressure(in)            87
Visibility(mi)         109
Wind_Direction         189
Wind_Speed(mph)        810
Precipitation(in)     7838
Weather_Condition      123
dtype: int64

In [11]:
missing_val = missing_val.reset_index()
missing_val

                index      0
0       Street_Number  26817
1        Airport_Code      7
2   Weather_Timestamp     63
3      Temperature(F)     98
4       Wind_Chill(F)   7964
5         Humidity(%)    100
6        Pressure(in)     87
7      Visibility(mi)    109
8      Wind_Direction    189
9     Wind_Speed(mph)    810
10  Precipitation(in)   7838
11  Weather_Condition    123

In [12]:
missing_val.rename(columns={'index':'Field_NaN', 0:'Count'}, inplace=True)
missing_val

            Field_NaN  Count
0       Street_Number  26817
1        Airport_Code      7
2   Weather_Timestamp     63
3      Temperature(F)     98
4       Wind_Chill(F)   7964
5         Humidity(%)    100
6        Pressure(in)     87
7      Visibility(mi)    109
8      Wind_Direction    189
9     Wind_Speed(mph)    810
10  Precipitation(in)   7838
11  Weather_Condition    123

### Checking for duplicates

In [13]:
# Check if there are duplicate entries or records
dallas_city[dallas_city.duplicated()]

Empty DataFrame
Columns: [Severity, Start_Time, End_Time, Start_Lat, Start_Lng, End_Lat, End_Lng, Distance(mi), Description, Street_Number, Street_Name, Street_Side, County, Zipcode, Airport_Code, Weather_Timestamp, Temperature(F), Wind_Chill(F), Humidity(%), Pressure(in), Visibility(mi), Wind_Direction, Wind_Speed(mph), Precipitation(in), Weather_Condition, Amenity, Bump, Crossing, Give_Way, Junction, No_Exit, Railway, Roundabout, Station, Stop, Traffic_Calming, Traffic_Signal, Turning_Loop, Sunrise_Sunset, Civil_Twilight, Nautical_Twilight, Astronomical_Twilight]
Index: []

**Note: There are no duplicates in the data**

## Investigating Columns

### 1. Start_Time & End_Time

Confirm if _'Start_Time'_ and _'End_Time'_ are of valid Datetime type

In [98]:
# If this code returns error then the Start_Time is not a valid datetime 
dallas_city.loc['A-11786', 'Start_Time'].day_name()

AttributeError: 'str' object has no attribute 'day_name'

### Convert to Datetime type

In [106]:
dallas_city['Start_Time'] = pd.to_datetime(dallas_city['Start_Time'])
dallas_city['End_Time'] = pd.to_datetime(dallas_city['End_Time'])

dallas_city.head(5)

,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Description,Street_Number,Street_Name,Street_Side,County,Zipcode,Airport_Code,Weather_Timestamp,Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Direction,Wind_Speed(mph),Precipitation(in),Weather_Condition,Amenity,Bump,Crossing,Give_Way,Junction,No_Exit,Railway,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
A-11786,2,2016-11-30 15:29:48,2016-11-30 21:29:48,32.84365,-96.77463,32.81833,-96.78806,1.915,Between Mockingbird Ln/Exit 3 and Knox St/Hend...,Not Available,US-75 S,R,Dallas,75205,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11787,2,2016-11-30 15:41:16,2016-11-30 21:41:16,32.84662,-96.63736,32.84640,-96.63711,0.021,At La Prada Dr/Exit 9 - Accident.,Not Available,I-635 S,R,Dallas,75228,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11794,3,2016-11-30 16:16:05,2016-11-30 22:16:05,32.79385,-96.70278,32.79498,-96.69424,0.502,At Jim Miller Rd/Exit 51 - Accident.,Not Available,R L Thornton Fwy E,R,Dallas,75228,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,True,False,False,False,False,False,False,False,False,Day,Day,Day,Day
A-11795,3,2016-11-30 16:16:05,2016-11-30 22:16:05,32.85710,-96.77046,32.84623,-96.77330,0.769,Between Caruth Haven Ln/Exit 4 and Lovers Ln/E...,Not Available,Southwestern Blvd,R,Dallas,75225,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,True,False,False,False,False,False,False,False,False,True,False,Day,Day,Day,Day
A-11798,3,2016-11-30 16:21:05,2016-11-30 22:21:05,32.87684,-96.81001,32.88004,-96.80963,0.222,At Walnut Hill Ln - Accident.,Not Available,Dallas North Tollway N,R,Dallas,75225,KDAL,2016-11-30 15:53:00,61.0,NaN,22.0,30.01,10.0,NNW,4.6,NaN,Clear,False,False,False,False,False,False,False,False,False,False,False,False,False,Day,Day,Day,Day

In [124]:
df1 = (dallas_city['End_Time'] - dallas_city['Start_Time'])

### 2. Description: Confirm whether there is a uniform parttern we can extract

In [82]:
dallas_city.loc['A-2844612':'A-2845068', 'Description']

ID
A-2844612                 At Northwest Hwy/Exit 11 - Accident.
A-2844627    At Laureland Rd/Exit 420 - Accident. Two lanes...
A-2844632                     At Dallas North Tlwy - Accident.
A-2845067    At Royal Ln/Exit 7 - Accident. Two lanes blocked.
A-2845068     At Hi Line Dr/Exit 429 - Accident. Lane blocked.
Name: Description, dtype: object

### Note: Looking at a subset of the 'Description' series, we can infer that it might follow a certain pattern that may or may not include road blockage and traffic condition details.

Hence, we will look at this more closely by splitting the entire string object and expand into new columns.

In [77]:
df = dallas_city['Description'].str.split('.', 1, expand=True)
df

,0,1
ID,,
A-11786,Between Mockingbird Ln/Exit 3 and Knox St/Hend...,
A-11787,At La Prada Dr/Exit 9 - Accident,
A-11794,At Jim Miller Rd/Exit 51 - Accident,
A-11795,Between Caruth Haven Ln/Exit 4 and Lovers Ln/E...,
A-11798,At Walnut Hill Ln - Accident,
...,...,...
A-2844612,At Northwest Hwy/Exit 11 - Accident,
A-2844627,At Laureland Rd/Exit 420 - Accident,Two lanes blocked.
A-2844632,At Dallas North Tlwy - Accident,
A-2845067,At Royal Ln/Exit 7 - Accident,Two lanes blocked.
A-2845068,At Hi Line Dr/Exit 429 - Accident,Lane blocked.

In [78]:
df.rename(columns={1:'Impact'}, inplace=True)

In [79]:
df[['Description', 'Status']] = df[0].str.rsplit(' - ', 1, expand=True)
df.drop(columns=[0], inplace=True)

In [80]:
pd.DataFrame(df['Status'].value_counts()).reset_index().rename(columns={'index':'Status', 'Status':'Count'})

                                                 Status  Count
0                                              Accident  11190
1                           Road closed due to accident    464
2                                               I-35E S    188
3     LBJ Fwy W from Exit 25 (I-635) to I-35E/Exit 2...    112
4                                             LBJ Fwy W    112
...                                                 ...    ...
1263  US-67 N from I-45/US-75/Exit 46 (I-30) to Jim ...      1
1264  R L Thornton Fwy N is closed from Laureland Rd...      1
1265  I-35E S from Motor St/Exit 431 (I-35E) to Hi L...      1
1266  LBJ Fwy E from US-67/Exit 464 (I-20) to Housto...      1
1267           Multi-vehicle accident involving vehicle      1

[1268 rows x 2 columns]

In [81]:
pd.DataFrame(df['Impact'].value_counts()).reset_index().rename(columns={'index':'Impact', 'Impact':'Count'})

                                                Impact  Count
0                                                       37786
1                                   Two lanes blocked.    633
2                                  Right lane blocked.    561
3                                        Lane blocked.    483
4                                   Left lane blocked.    459
..                                                 ...    ...
230                        PAUL ST Expect long delays.      1
231  F. Hawn Fwy E - US-175 E from Elam Rd (US-175)...      1
232  F. Hawn Fwy E - US-175 E from TX-12 Loop (US-1...      1
233                           TATE Drive with caution.      1
234                             Oil spillage accident.      1

[235 rows x 2 columns]

In [52]:
df['Description'].value_counts()

Slow traffic on I-635 W                                                       644
Slow traffic on I-635 E                                                       456
Stationary traffic on I-635 W                                                 421
Stationary traffic on I-635 E                                                 358
Stationary traffic on I-35E N - US-77 N                                       320
                                                                             ...
Accident from exit [464B] to I-20 W                                             1
Incident on LONGBRANCH LN near GREAT TRINITY FOREST WAY Drive with caution      1
Incident on N CENTRAL SERV NB near MCCOMMAS BLVD Drive with caution             1
Incident on BONNIE VIEW RD near SUNNYVALE ST Drive with caution                 1
Ramp to I-45 Northbound and Main St Westbound and Elm St Westbound              1
Name: Description, Length: 15443, dtype: int64

In [69]:
df.isna().sum()

Impact             0
Description        0
Status         24448
dtype: int64

### Note: Although there are important details in the description pertaining to traffic impact, road blockage and type of incident , it is really hard to tell and extract these as it does not follow a particular pattern in contrary to what we assumed.

### 2. Street Number

In [67]:
dallas_city['Street_Number'].describe()

count    14798.000000
mean      5072.287133
std       3871.460201
min          1.000000
25%       2200.000000
50%       4031.000000
75%       7539.750000
max      39636.000000
Name: Street_Number, dtype: float64

### Note: The Street number is considered as a **numerical data** rather than categorical.

This is because the statistical summary such as Mean, Median and Standard Deviation can be calculated in this series, which should not be the case since we do not expect to make calculations on Street Numbers.

### Replacing NAN values in the Street Number Attribute

In [83]:
dallas_city['Street_Number'].replace(np.nan, "Not Available", inplace=True)

In [84]:
dallas_city['Street_Number'].describe()

count             41615
unique             4317
top       Not Available
freq              26817
Name: Street_Number, dtype: object

By changing the np.nan value, which is of type float64, we also changed the entire series as a categorical data. We expect to not see the _'Street_Number'_ column when displaying the statistical summary of the numerical data.

In [85]:
dallas_city.describe()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,41615.000000,41615.000000,41615.000000,41615.000000,41615.000000,41615.000000,41517.000000,33651.000000,41515.000000,41528.000000,41506.000000,40805.000000,33777.000000
mean,2.168161,32.810865,-96.796576,32.810890,-96.796539,0.519945,67.786858,65.893694,61.806239,29.546073,9.507942,8.955949,0.006056
std,0.423263,0.086094,0.070059,0.085941,0.070672,0.777038,17.011423,19.079469,20.651219,0.316948,2.069479,5.062563,0.049506
min,1.000000,32.620309,-97.072350,32.618569,-97.094565,0.000000,1.000000,-12.000000,9.000000,28.720000,0.000000,0.000000,0.000000
25%,2.000000,32.749444,-96.839399,32.750629,-96.838176,0.073000,55.000000,54.000000,46.000000,29.320000,10.000000,6.000000,0.000000
50%,2.000000,32.801460,-96.800290,32.801264,-96.801068,0.243000,70.000000,69.000000,62.000000,29.480000,10.000000,8.100000,0.000000
75%,2.000000,32.887905,-96.755401,32.887405,-96.753867,0.672000,81.000000,80.000000,79.000000,29.730000,10.000000,12.000000,0.000000
max,4.000000,33.015130,-96.556901,33.023800,-96.557576,10.622000,105.100000,102.000000,100.000000,30.830000,13.000000,211.000000,2.100000

## Display records with NaN values in attribute "Weather Condition" <hr>

In [ ]:
dallas_city[dallas_city['Weather_Condition'].isna()].head()

In [ ]:
dallas_city.Weather_Condition.value_counts()

In [ ]:
#Exploring accidents with Weather Conditions 
dallas_city[dallas_city['Weather_Condition'].isna()!=True].head()

In [ ]:
# Exploring accidents where the Weather Condition is Mostly Cloudy
dallas_city[dallas_city['Weather_Condition']=='Mostly Cloudy'].head()

In [ ]:
# Checking the number of accidents that fall under each Severity Levels under Mostly Cloudly weather condition

dallas_city[dallas_city['Weather_Condition']=='Mostly Cloudy']['Severity'].value_counts()

## Using Advanced Matplotlib API <hr>

In [ ]:
fig, ax = plt.subplots(2, 2, figsize=(20,10))
ax[0][0].hist(dallas_city.Severity, edgecolor='black', bins=10)
ax[0][0].set_xlabel('Accident Severity')
ax[0][0].set_ylabel('Frequency of Accidents')
ax[0][0].set_title('Frequency vs Severity')
# ax[0][1].scatter(dallas_city.ID,dallas_city.Severity)
# ax[0][1].set_xlabel('Accident Severity')
# ax[0][1].set_ylabel('Frequency of Accidents')
# ax[0][1].set_title('Frequency vs Severity')
plt.show()

In [ ]:
dallas_city.hist(bins=30, figsize=(20,15), color='green', edgecolor='black')
plt.show()

In [ ]:
plt.hist(dallas_city.Severity, bins=[1,2,3,4,5], edgecolor='black', rwidth=0.8, color='blue')
plt.title("Frequency vs Severity")
plt.xlabel("Severity")
plt.ylabel("Frequency of Accidents")
plt.show()

In [ ]:
dallas_city[['Severity','Description']]